// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIk8mSnyqNgT7m79AsqH9eUTPunDbJWxM',
    appId: '1:367707264187:web:9f0ac0fc207a543782059e',
    messagingSenderId: '367707264187',
    projectId: 'hockey-family',
    authDomain: 'hockey-family.firebaseapp.com',
    storageBucket: 'hockey-family.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqr-lbWdXx59PDGOcPBqn2VgqdAbF8qI',
    appId: '1:367707264187:android:d95a01cbfa700ddd82059e',
    messagingSenderId: '367707264187',
    projectId: 'hockey-family',
    storageBucket: 'hockey-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEUW9FJfiZrKbGRqJN8dZeI77Vp8UzD6I',
    appId: '1:367707264187:ios:7c1a6227af43521b82059e',
    messagingSenderId: '367707264187',
    projectId: 'hockey-family',
    storageBucket: 'hockey-family.firebasestorage.app',
    iosBundleId: 'com.example.hockeyFamily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEUW9FJfiZrKbGRqJN8dZeI77Vp8UzD6I',
    appId: '1:367707264187:ios:7c1a6227af43521b82059e',
    messagingSenderId: '367707264187',
    projectId: 'hockey-family',
    storageBucket: 'hockey-family.firebasestorage.app',
    iosBundleId: 'com.example.hockeyFamily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIk8mSnyqNgT7m79AsqH9eUTPunDbJWxM',
    appId: '1:367707264187:web:661d6b54e564d85282059e',
    messagingSenderId: '367707264187',
    projectId: 'hockey-family',
    authDomain: 'hockey-family.firebaseapp.com',
    storageBucket: 'hockey-family.firebasestorage.app',
  );

}